name: Build and Publish Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  MAUTRIX_GMESSAGES_VERSION: 0.4.2

jobs:
  build-publish:
    uses: halkeye/halkeye/.github/workflows/build-upstream-docker.yaml@main
    secrets: inherit
    permissions:
      contents: write
      packages: write
    with:
      upstream_version: v${{env.MAUTRIX_GMESSAGES_VERSION}}
      upstream_repo: https://github.com/mautrix/gmessages
      run_number: ${{ github.run_number }}
      username: ${{ github.repository_owner }}
      repository: ${{ github.repository }}
